@startuml
skinparam linetype ortho

package fare {
    package ordinary {
        class OneWayFareService <<Service>>
        class RoundTripFareService <<Service>>
    }
    package group {
        class GroupFareService <<Service>>
    }
}


class FareYen


fare -> FareYen

@enduml